name: FTSSystem
version: 1.7.1
main: de.ftscraft.ftssystem.main.FtsSystem
author: halberfan
api-version: 1.17
depend:
    - FTSEngine
softdepend:
    - LuckPerms
    - Factions
    - MassiveCore
    - ChestShop
    - dynmap
    - FTSPest
    - Towny

commands:
    ftssystem:
    channel:
    umfrage:
    togglesidebar:
    pu:
    tutorialbook:
    akte:
    broadcast:
        aliases: [bc]
    roleplay:
        aliases: [rp]
    passwort:
    premium:
    fts:
    wartung: