name: FTSSystem
version: 1.1.3.0
main: de.ftscraft.ftssystem.main.FtsSystem
author: halberfan
api-version: 1.13
depend:
    - FTSEngine
    - FTSSurvival
softdepend:
    - Disease
    - LuckPerms
    - Factions
    - MassiveCore

commands:
    ftssystem:
    channel:
    umfrage:
    togglesidebar:
    pu:
    tutorialbook:
    akte:
    roleplay:
    passwort: