name: FTSSystem
version: ${project.version}
main: de.ftscraft.ftssystem.main.FtsSystem
author: halberfan
api-version: '1.20'
depend:
  - FTSUtils
softdepend:
  - LuckPerms
  - Essentials
  - Towny
  - PlaceholderAPI
  - FTSEngine

commands:
  ftssystem:
    description: Kleinigkeiten für Teamler
  umfrage:
    description: Erstellt eine Umfrage
  pu:
    description: Öffnet das Punishment Menü für Teamler
  tutorialbook:
    description: Gibt das Tutorialbuch
  akte:
    description: Zeigt dir deine Akte an
  broadcast:
    aliases: [ bc ]
    description: Schalte eine Nachricht die an alle Spieler gesendet wird
  passwort:
    description: Gebe das Passwort ein um dich freizuschalten
  checkcv:
    description: Überprüft die angegebene CV im Ausweis und promotet ggf. zum Bürger
  premium:
    description: Allerhand Nützlichkeiten für Premium-Spieler
  voteban:
    description: Startet oder stimmt für einen Voteban eines Spielers
  fts:
    description: Allerhand Nützlichkeiten rund um FTS
  wartung:
    description: Schaltet den Server in den Wartungsmodus.
  cc:
    permission: ftssystem.chat.team
    description: Der Team-Chat
  g:
    description: Schalte den Global-Chat als deinen aktiven Channel
  l:
    description: Schalte den Lokal-Chat als deinen aktiven Channel
  ooc:
    description: Schalte den OOC-Chat als deinen aktiven Channel
  fl:
    description: Schalte den Flüster-Chat als deinen aktiven Channel
  sc:
    description: Schalte den Schreien-Chat als deinen aktiven Channel
  tc:
    description: Der Towny Chat
  setvotehome:
    description: Setzt den Punkt deines Vote-Homes
  votehome:
    description: Teleportiert, wenn du es freigeschaltet hast, dich zu deinem Vote-Home
  durchsage:
    description: Lässt neue Durchsagen einfügen und welche löschen
  radius:
    description: Zeigt den Radius deines aktiven Channels an
  travel:
    description: Befehl exklusiv für die Konsole
    permission: ftssystem.console
  repair:
    description: Repariert das Item in der Hand des angegebenen Spielers
    usage: /repair [Spieler]
    permission: ftssystem.console
  xpstore:
    usage: /xpstore [Spieler]
    permision: ftssystem.console
  rp:
    usage: /rp
    description: Toggelt den RP-Modus
  deckname: