name: FTSSystem
version: 1.0.1
main: de.ftscraft.ftssystem.main.FtsSystem
author: halberfan
api-version: 1.14
depend: [Vault]

commands:
    ftssystem:
    channel:
    umfrage:
    togglesidebar:
    pu:
    tutorialbook:
    akte: