name: FTSSystem
version: 1.3
main: de.ftscraft.ftssystem.main.FtsSystem
author: halberfan
api-version: 1.13
depend:
    - FTSEngine
softdepend:
    - Disease
    - LuckPerms
    - Factions
    - MassiveCore
    - ChestShop

commands:
    ftssystem:
    channel:
    umfrage:
    togglesidebar:
    pu:
    tutorialbook:
    akte:
    roleplay:
        aliases: [rp]
    passwort:
    premium:
    fts: