name: FTSSystem
version: 1.10.0.2
main: de.ftscraft.ftssystem.main.FtsSystem
author: halberfan
api-version: '1.20'
depend:
    - FTSEngine
softdepend:
    - LuckPerms
    - Factions
    - MassiveCore
    - ChestShop
    - dynmap
    - FTSPest
    - Towny

commands:
    ftssystem:
    channel:
    umfrage:
    togglesidebar:
    pu:
    tutorialbook:
    akte:
    broadcast:
        aliases: [bc]
    roleplay:
        aliases: [rp]
    passwort:
    checkcv:
    premium:
    voteban:
    fts:
    wartung:

    tc:
        permission: ftssystem.chat.team
        description: Der Team-Chat
    g:
    l:
    ooc:
    fl:
    sc:
    setvotehome:
    votehome:
    durchsage: